var paper = [];
var color = null;

color = [
        "#d63126", 
        "#f58c5b", 
        "#fcd58a", 
        "#d8e58c",
        "#92c960",
        "#19984f"
        ];

window.onload = function (){
        var iterator = 0;
        var divs = document.getElementsByClassName("rectangles");

        for (var i = 0; i < divs.length; i++){
            paper[i] = Raphael(divs[i], 270, 33, null);
       }

        //var rects = [];
        for (var i = 6; i < 270; i+= 44) {

            console.log(i);
    
                    for (var j = 0; j < paper.length; j++) {
                            var rect = paper[j].rect(i, 6, 42, 15).attr({
                                "fill":color[iterator],
                                "stroke-width": "0"
                            });

                    //stroke around rect
                  $(document).ready(function () {
                      if(window.location.href.indexOf("#month") > -1) {
                          var rect = paper[j].ellipse(159, 14, 13, 13).attr({
                                "stroke-width": "0",
                                "stroke": "#669966",
                                "fill":"#fff"
                            });
                      } else if(window.location.href.indexOf("#week") > -1) {
                          var rect = paper[j].ellipse(115, 14, 13, 13).attr({
                                "stroke-width": "0",
                                "stroke": "#669966",
                                "fill":"#fff"
                            });
                      } else {
                        var rect = paper[j].ellipse(204, 14, 13, 13).attr({
                                "stroke-width": "0",
                                "stroke": "#669966",
                                "fill":"#fff"

                            });
                      }
                  });     
                            

                            // console.log("i = " + i + " " + "j = " +j);
                        }
                        iterator ++;

        }
}

function Bubble(){
  var x=document.getElementById("infoText");

  var infoText = [
  'Fun Fact: Fertilisers used in growing feed crops for cattle produce the most potent of all greenhouse gases causing climate change.', 
  'Fun Fact: Studies have linked vegetarian diets with a decreased risk of heart disease, diabetes, high blood pressure, obesity, and colon cancer.',
  'Fun Fact: Most crops are grown using fertilizer, pesticides and herbicides. Organic food is raised naturally, which results in healthier food.', 
  'Fun Fact: If all Americans ate no meat or cheese one day a week it would be as benefitial to the environment as taking 7.6 million cars off the road.', 
  'Fun Fact: Increasing intake of fruits, veggies, beans and grains benefits not only the environment but also your health and your wallet.',
  'Fun Fact: About 40% of food available in the United States is discarded each year, leaving a huge environmental footprint.',
  'Fun Fact: Producing 1kg of beef results in more CO2 emissions than going for a three-hour drive, while leaving all your lights on at home.',
  'Fun Fact: Red meats (beef and pork) cause 3 times more carbom emmissions then sea food',
  'Fun Fact: Nearly 1/5 of all green house gas is generated by live stock production',
  'Fun Fact: Dairy cows used to produce cheese emit large quantities of methane, which has a global warming impact 25 times higher than carbon.',
  'Fun Fact: Cow farts and manure cause methane. Methane is 20 times more poisonous then CO2.', 
  'Fun Fact: It takes about 10 pounds of milk to produce 1 pound of hard cheese, and dairy cows emmit lots of methane into the air.', 
  'Fun Fact: 30% of the land on earth is directly or indirectly devoted to the animals we all eat',
  'Fun Fact: In 2010, the UN identified animal agriculture as one of the most significant drivers of environmental pressures and climate change'
  ];

  x.innerHTML=infoText[ Math.floor(Math.random() * infoText.length )];
}

$(document).on("pageshow", function() {
    Bubble();
});


